variables:
  APP_IMAGE_REPO: ${REGISTRY_HOST}/${CI_PROJECT_NAMESPACE}/${CI_PROJECT_NAME}

workflow:
  rules:
    - if: $CI_COMMIT_TAG
      variables:
        APP_VERSION: ${CI_COMMIT_TAG}
    - when: never

stages:
  - docker-build

.base: &base
  tags:
    - k8s

.docker-build:
  <<: *base
  stage: docker-build
  image: docker:20.10
  services:
    - docker:20-dind
  variables:
    BUILD_PATH: .
  before_script:
    - docker login ${REGISTRY_HOST} -u ${REGISTRY_USER} -p ${REGISTRY_TOKEN}
  script:
    - cd ${BUILD_PATH}
    - docker build --build-arg REGISTRY_HOST_VAR=${REGISTRY_HOST} -t ${APP_IMAGE_REPO}:${APP_VERSION} --rm .
    - docker push ${APP_IMAGE_REPO}:${APP_VERSION}

docker-build:
  extends: .docker-build