name: Build

on:
  release:
    types: [published]  # 只在发布 release 时触发

jobs:

  docker-build:
    runs-on: ubuntu-latest
    env:
      PLATFORMS: linux/amd64,linux/arm64
    steps:

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Get release version
        id: get_version
        run: echo "::set-output name=VERSION::${{ github.event.release.tag_name }}"

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          platforms: ${{ env.PLATFORMS }}
          push: true
          tags: |
            yiniot/openresty-base:latest
            yiniot/openresty-base:${{ steps.get_version.outputs.VERSION }}
